# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "thunderbolt" "usb_storage" "sd_mod" "rtsx_pc_sdmmc" ];
  boot.initrd.kernelModules = [ "dm-snapshot" "cryptd" ];
#  boot.initrd.luks.devices."cryptroot".device = "/dev/disk/by-label/LUKS";
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

#  fileSystems."/" =
#    { device = "/dev/disk/by-label/ROOT";
#      fsType = "ext4";
#    };
#
#
#  fileSystems."/boot" =
#    { device = "/dev/disk/by-label/BOOT";
#      fsType = "vfat";
#      options = [ "fmask=0077" "dmask=0077" ];
#    };
#
#  fileSystems."/home" =
#    { device = "/dev/disk/by-label/HOME";
#      fsType = "ext4";
#    };
#
#  swapDevices =
#    [ { device = "/dev/disk/by-label/SWAP"; }
#    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.enableAllFirmware = true;
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
